version: '3'
services:
  app:
    build: ./app
    ports:
     - "5000:5000"
    volumes:
     - ./app:/app
  redis:
    image: "redis:alpine"
  jupyter:
    build: ./jupyter
    volumes:
      -  ./jupyter:/app
    ports:
     - "8000:8888"
    entrypoint: jupyter lab --ip=0.0.0.0 --no-browser --notebook-dir=/app
