version: '3'
services:
  app:
    build: ./app
    ports:
     - "5000:5000"
    volumes:
     - ./app:/app
  redis:
    image: "redis:alpine"
  db:
    build: ./db
    command: mysqld --user=root --verbose
    volumes:
      - ./db:/app
    environment:
      MYSQL_DATABASE: "test"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    # container_name: database.dev
    ports:
    - "13306:3306"
  jupyter:
    build: ./jupyter
    volumes:
      -  ./jupyter:/app
    ports:
     - "8000:8888"
    entrypoint: jupyter lab --ip=0.0.0.0 --no-browser --notebook-dir=/app
